name: Build and Test with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#      - name: setup ubuntu
#        run: |
#          sudo apt update
#          sudo apt upgrade -y

      - name: start mysql
        run: sudo /etc/init.d/mysql start

      - name: setup mysql
        run: |
          mysql -h localhost -u root -proot -e "CREATE DATABASE webappdb;"
          mysql -h localhost -u root -proot -e "CREATE USER 'csye6225'@'%' IDENTIFIED BY 'PASSword123!';"
          mysql -h localhost -u root -proot -e "GRANT ALL PRIVILEGES ON webappdb.* TO 'csye6225'@'%';"

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean with Maven
        run: mvn clean install

      - name: Run test
        run: mvn test

