name: Packer Build AMI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - run: sudo /etc/init.d/mysql start
      - name: Connect to MySQL server
        run: |
          mysql -h localhost -u root -proot -e "CREATE DATABASE webappdb;"
          mysql -h localhost -u root -proot -e "CREATE USER 'csye6225'@'%' IDENTIFIED BY 'PASSword123!';"
          mysql -h localhost -u root -proot -e "GRANT ALL PRIVILEGES ON webappdb.* TO 'csye6225'@'%';"

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean with Maven
        run: mvn clean

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Build AMI
        run: |
          packer init ./ami.pkr.hcl
          packer fmt ./ami.pkr.hcl
          packer validate ./ami.pkr.hcl
          packer build ./ami.pkr.hcl